package crud_tugas;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import crud_tugas.koneksi;
import java.awt.event.KeyEvent;




public class Login extends javax.swing.JFrame {
    koneksi con;
    private Integer idpegawai;
    int l = 0;
    /**
     * Creates new form Login
     */
    
    
    public Login() {
        initComponents();
        con = new koneksi();
        con.Class();
        this.setLocationRelativeTo(null);
    }
    
    private void nextframe() throws SQLException{
        System.out.println(l);
        if("1".equals(String.valueOf(l))){
            new Admin().setVisible(true);
        } else if("2".equals(String.valueOf(l))){
            new Kasir().setVisible(true);
        } else if("3".equals(String.valueOf(l))){
            new CrudBarangGudang().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Elu Siapa ?");
        }
    }
    
    private void masuk(){
        
        try{
            con.ss = (Statement) con.cc.createStatement();
            String byr = "Select * From userlevel Where id_user='"+txtidpeg.getText()+"' And pass_user= '"+txtpassword.getText()+"'";
            con.rr = con.ss.executeQuery(byr);

            if(con.rr.next()){
                idpegawai= con.rr.getInt(1);
                l=l+ con.rr.getInt(4);
            }
            if(con.rr.getRow()!=0){
                nextframe.set_id(idpegawai);
                JOptionPane.showMessageDialog(null, "Login Sukses");
                nextframe();
                this.dispose();
            }

            else{
                JOptionPane.showMessageDialog(null, "Username atau password salah");
                txtidpeg.setText("");
                txtpassword.setText("");
                txtidpeg.requestFocus();
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(e);
            txtidpeg.setText("");
            txtpassword.setText("");
            txtidpeg.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidpeg = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lalogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame1"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidpeg.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        txtidpeg.setBorder(null);
        txtidpeg.setOpaque(false);
        getContentPane().add(txtidpeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 330, 20));

        txtpassword.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.setOpaque(false);
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 330, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 151, 17, 20));

        lalogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_ res 1280 x 720-04.png"))); // NOI18N
        lalogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laloginMouseClicked(evt);
            }
        });
        getContentPane().add(lalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            masuk();
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void laloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laloginMouseClicked
        masuk();
    }//GEN-LAST:event_laloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lalogin;
    private javax.swing.JTextField txtidpeg;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
